### PR TITLE
#115230243 refactor signup and login pages

### PR DESCRIPTION
**Pull request by collinmutembei**
#### What does this PR do?

Implements changes on the signup and login page to allow for a more appealing interface as well as increase the usability of `Limber`
#### Description of Task to be completed?
- [x] Allow for easy back and forth navigation from the projects landing page, the signup page and the login page.
- [x] Implement password length enforcement by disallowing signup for passwords that have an entropy of less that 8 characters
#### How should this be manually tested?

Visit the following pages on the projects' [website](http://dev.limberapp.xyz)

> landing page > signup page > Already have an account
> landing page > login page > Don't have an account
> landing page > signup page > Limber
> landing page > login page > Limber
#### Any background context you want to provide?

The signup and login buttons remain disabled untill the signup and login forms (respectively) are valid.
#### What are the relevant pivotal tracker stories?

The correspoding story on `PT` can be viewed [here](https://www.pivotaltracker.com/story/show/115230243)
#### Screenshots

screen shot 2016-03-22 at 12 32 01
screen shot 2016-03-22 at 12 15 29
screen shot 2016-03-22 at 12 15 07
#### Questions

Having the button stay disabled from the get go till the form is filled validly could leave the user wondering why the button does not work, and consequently making them abandon `Limber`. How do you suggest we make the balance between making the website usable and ensuring we have adequate validation on the front-end?

### CODE REVIEW

**Comment by andela-anandaa** [comment]
@andela-cmutembei -- did we say that the _Login_ button should be a different color? (Transparent with white border)

**Comment by collinmutembei** [comment]
@andela-anandaa The button hasn't changed color, that's how it appears when disabled. Which is the case before the form is filled validly.

**Comment by collinmutembei** [comment]
@andela-anandaa I have noticed that the call to action item is from a different story, which can be found [here](https://www.pivotaltracker.com/story/show/115229619)

**Comment by collinmutembei** [comment]
@andela-anandaa we can review this [`PR`](https://github.com/andela/limber/pull/44) whenever you are ready

**Pull request merged**
